## config/database.yml ##

 development:
   adapter: postgresql
   database: mmt_development
   pool: 5
   timeout: 5000

 test:
   adapter: postgresql
   database: mmt_test
   pool: 5
   timeout: 5000

 production:
   adapter: postgresql
   database: mmt_production
   pool: 5
   timeout: 5000
   
